Traceback (most recent call last):
  File "main.py", line 173, in <module>
    main()
  File "main.py", line 161, in main
    mp.spawn(main_moco.main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
  File "/home/sci/jbergquist/python_dev_env/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/sci/jbergquist/python_dev_env/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/sci/jbergquist/python_dev_env/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:
-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/home/sci/jbergquist/python_dev_env/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/collab/deekshith.dade/moco_project/main_moco.py", line 138, in main_worker
    train(pre_train_loader, model, criterion, optimizer, epoch, args)
  File "/home/collab/deekshith.dade/moco_project/main_moco.py", line 200, in train
    'acc@5': acc5[0]
  File "/home/sci/jbergquist/python_dev_env/lib/python3.7/site-packages/wandb/sdk/lib/preinit.py", line 36, in preinit_wrapper
    raise wandb.Error(f"You must call wandb.init() before {name}()")
wandb.errors.Error: You must call wandb.init() before wandb.log()